export { DefaultCarousel } from "./DefaultCarousel"
export { Trending } from "./Trending"
export { UpComing } from "./UpComing"
export { NowPlaying } from "./NowPlaying"
export { TopRated } from "./TopRated"